### PR TITLE
Bug fix for setHostName

### PR DESCRIPTION
**Pull request by DennisB66**

### CODE REVIEW

**Comment by DennisB66** [comment]
Hi Sudheer,

I had some strange effects using your library and needed some fixes. Let me know what you think.

Kind regards, Dennis

**Comment by technofreakz** [comment]
Hello..

I think some one  has modified, better version is included in Arduino..

What issues you facing ?



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by DennisB66** [comment]
Hi, the issue is that the setHostName in your code does not check for a buffer overrun. If you use a hostname longer than 6 characters then it’s is overwriting other memory.

 

I think Arduino still provides the same version, only your code extends with setHostName en getHostName (where Arduino does not), but has an issue in my opinion.

 

Van: Sudheer T [mailto:notifications@github.com] 
Verzonden: zondag 20 augustus 2017 08:24
Aan: technofreakz/Ethernet <Ethernet@noreply.github.com>
CC: DennisB66 <dennis.buis@home.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [technofreakz/Ethernet] Bug fix for setHostName (#2)

 

Hello..

I think some one has modified, better version is included in Arduino..

What issues you facing ?



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by technofreakz** [comment]
ok,, I will work on this fix on weekend..



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
